// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: proto/adapter.proto

package adapter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Adapter_ReserveTrip_FullMethodName = "/adapter.Adapter/ReserveTrip"
	Adapter_Ack_FullMethodName         = "/adapter.Adapter/Ack"
	Adapter_AtDock_FullMethodName      = "/adapter.Adapter/AtDock"
	Adapter_OnBoat_FullMethodName      = "/adapter.Adapter/OnBoat"
	Adapter_OffBoat_FullMethodName     = "/adapter.Adapter/OffBoat"
	Adapter_BoatStatus_FullMethodName  = "/adapter.Adapter/BoatStatus"
	Adapter_Arrived_FullMethodName     = "/adapter.Adapter/Arrived"
)

// AdapterClient is the client API for Adapter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The Adapter service definition
type AdapterClient interface {
	// A bi-directional streaming RPC.
	// The MockLogic(gRPC client) receives a Reserve request that an API client has sent
	ReserveTrip(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Empty, ReserveTripMessage], error)
	// A bi-directional streaming RPC.
	// The MockLogic(gRPC client) sends an Acknowledgement that a previously sent
	// ReserveMessage is being handled
	Ack(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AckMessage, Empty], error)
	// A bi-directional streaming RPC.
	// The MockLogic(gRPC client) receives an AtDock message that an API client has sent
	AtDock(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Empty, AtDockMessage], error)
	// A bi-directional streaming RPC.
	// The MockLogic(gRPC client) receives an OnBoat message that an API client has sent
	OnBoat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Empty, OnBoatMessage], error)
	// A bi-directional streaming RPC.
	// The MockLogic(gRPC client) receives an OffBoat message that an API client has sent
	OffBoat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Empty, OffBoatMessage], error)
	// A bi-directional streaming RPC.
	// The MockLogic(gRPC client) sends an BoatStatus message that the Adapter will
	// broadcast
	BoatStatus(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BoatStatusMessage, Empty], error)
	// A bi-directional streaming RPC.
	// The MockLogic(gRPC client) sends an Arrived message that the Adapter will send
	// to the API client
	Arrived(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ArrivedMessage, Empty], error)
}

type adapterClient struct {
	cc grpc.ClientConnInterface
}

func NewAdapterClient(cc grpc.ClientConnInterface) AdapterClient {
	return &adapterClient{cc}
}

func (c *adapterClient) ReserveTrip(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Empty, ReserveTripMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Adapter_ServiceDesc.Streams[0], Adapter_ReserveTrip_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, ReserveTripMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Adapter_ReserveTripClient = grpc.BidiStreamingClient[Empty, ReserveTripMessage]

func (c *adapterClient) Ack(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AckMessage, Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Adapter_ServiceDesc.Streams[1], Adapter_Ack_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AckMessage, Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Adapter_AckClient = grpc.BidiStreamingClient[AckMessage, Empty]

func (c *adapterClient) AtDock(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Empty, AtDockMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Adapter_ServiceDesc.Streams[2], Adapter_AtDock_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, AtDockMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Adapter_AtDockClient = grpc.BidiStreamingClient[Empty, AtDockMessage]

func (c *adapterClient) OnBoat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Empty, OnBoatMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Adapter_ServiceDesc.Streams[3], Adapter_OnBoat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, OnBoatMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Adapter_OnBoatClient = grpc.BidiStreamingClient[Empty, OnBoatMessage]

func (c *adapterClient) OffBoat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Empty, OffBoatMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Adapter_ServiceDesc.Streams[4], Adapter_OffBoat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, OffBoatMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Adapter_OffBoatClient = grpc.BidiStreamingClient[Empty, OffBoatMessage]

func (c *adapterClient) BoatStatus(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BoatStatusMessage, Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Adapter_ServiceDesc.Streams[5], Adapter_BoatStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BoatStatusMessage, Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Adapter_BoatStatusClient = grpc.BidiStreamingClient[BoatStatusMessage, Empty]

func (c *adapterClient) Arrived(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ArrivedMessage, Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Adapter_ServiceDesc.Streams[6], Adapter_Arrived_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ArrivedMessage, Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Adapter_ArrivedClient = grpc.BidiStreamingClient[ArrivedMessage, Empty]

// AdapterServer is the server API for Adapter service.
// All implementations must embed UnimplementedAdapterServer
// for forward compatibility.
//
// The Adapter service definition
type AdapterServer interface {
	// A bi-directional streaming RPC.
	// The MockLogic(gRPC client) receives a Reserve request that an API client has sent
	ReserveTrip(grpc.BidiStreamingServer[Empty, ReserveTripMessage]) error
	// A bi-directional streaming RPC.
	// The MockLogic(gRPC client) sends an Acknowledgement that a previously sent
	// ReserveMessage is being handled
	Ack(grpc.BidiStreamingServer[AckMessage, Empty]) error
	// A bi-directional streaming RPC.
	// The MockLogic(gRPC client) receives an AtDock message that an API client has sent
	AtDock(grpc.BidiStreamingServer[Empty, AtDockMessage]) error
	// A bi-directional streaming RPC.
	// The MockLogic(gRPC client) receives an OnBoat message that an API client has sent
	OnBoat(grpc.BidiStreamingServer[Empty, OnBoatMessage]) error
	// A bi-directional streaming RPC.
	// The MockLogic(gRPC client) receives an OffBoat message that an API client has sent
	OffBoat(grpc.BidiStreamingServer[Empty, OffBoatMessage]) error
	// A bi-directional streaming RPC.
	// The MockLogic(gRPC client) sends an BoatStatus message that the Adapter will
	// broadcast
	BoatStatus(grpc.BidiStreamingServer[BoatStatusMessage, Empty]) error
	// A bi-directional streaming RPC.
	// The MockLogic(gRPC client) sends an Arrived message that the Adapter will send
	// to the API client
	Arrived(grpc.BidiStreamingServer[ArrivedMessage, Empty]) error
	mustEmbedUnimplementedAdapterServer()
}

// UnimplementedAdapterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdapterServer struct{}

func (UnimplementedAdapterServer) ReserveTrip(grpc.BidiStreamingServer[Empty, ReserveTripMessage]) error {
	return status.Errorf(codes.Unimplemented, "method ReserveTrip not implemented")
}
func (UnimplementedAdapterServer) Ack(grpc.BidiStreamingServer[AckMessage, Empty]) error {
	return status.Errorf(codes.Unimplemented, "method Ack not implemented")
}
func (UnimplementedAdapterServer) AtDock(grpc.BidiStreamingServer[Empty, AtDockMessage]) error {
	return status.Errorf(codes.Unimplemented, "method AtDock not implemented")
}
func (UnimplementedAdapterServer) OnBoat(grpc.BidiStreamingServer[Empty, OnBoatMessage]) error {
	return status.Errorf(codes.Unimplemented, "method OnBoat not implemented")
}
func (UnimplementedAdapterServer) OffBoat(grpc.BidiStreamingServer[Empty, OffBoatMessage]) error {
	return status.Errorf(codes.Unimplemented, "method OffBoat not implemented")
}
func (UnimplementedAdapterServer) BoatStatus(grpc.BidiStreamingServer[BoatStatusMessage, Empty]) error {
	return status.Errorf(codes.Unimplemented, "method BoatStatus not implemented")
}
func (UnimplementedAdapterServer) Arrived(grpc.BidiStreamingServer[ArrivedMessage, Empty]) error {
	return status.Errorf(codes.Unimplemented, "method Arrived not implemented")
}
func (UnimplementedAdapterServer) mustEmbedUnimplementedAdapterServer() {}
func (UnimplementedAdapterServer) testEmbeddedByValue()                 {}

// UnsafeAdapterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdapterServer will
// result in compilation errors.
type UnsafeAdapterServer interface {
	mustEmbedUnimplementedAdapterServer()
}

func RegisterAdapterServer(s grpc.ServiceRegistrar, srv AdapterServer) {
	// If the following call pancis, it indicates UnimplementedAdapterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Adapter_ServiceDesc, srv)
}

func _Adapter_ReserveTrip_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AdapterServer).ReserveTrip(&grpc.GenericServerStream[Empty, ReserveTripMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Adapter_ReserveTripServer = grpc.BidiStreamingServer[Empty, ReserveTripMessage]

func _Adapter_Ack_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AdapterServer).Ack(&grpc.GenericServerStream[AckMessage, Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Adapter_AckServer = grpc.BidiStreamingServer[AckMessage, Empty]

func _Adapter_AtDock_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AdapterServer).AtDock(&grpc.GenericServerStream[Empty, AtDockMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Adapter_AtDockServer = grpc.BidiStreamingServer[Empty, AtDockMessage]

func _Adapter_OnBoat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AdapterServer).OnBoat(&grpc.GenericServerStream[Empty, OnBoatMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Adapter_OnBoatServer = grpc.BidiStreamingServer[Empty, OnBoatMessage]

func _Adapter_OffBoat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AdapterServer).OffBoat(&grpc.GenericServerStream[Empty, OffBoatMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Adapter_OffBoatServer = grpc.BidiStreamingServer[Empty, OffBoatMessage]

func _Adapter_BoatStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AdapterServer).BoatStatus(&grpc.GenericServerStream[BoatStatusMessage, Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Adapter_BoatStatusServer = grpc.BidiStreamingServer[BoatStatusMessage, Empty]

func _Adapter_Arrived_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AdapterServer).Arrived(&grpc.GenericServerStream[ArrivedMessage, Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Adapter_ArrivedServer = grpc.BidiStreamingServer[ArrivedMessage, Empty]

// Adapter_ServiceDesc is the grpc.ServiceDesc for Adapter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Adapter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "adapter.Adapter",
	HandlerType: (*AdapterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReserveTrip",
			Handler:       _Adapter_ReserveTrip_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Ack",
			Handler:       _Adapter_Ack_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "AtDock",
			Handler:       _Adapter_AtDock_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "OnBoat",
			Handler:       _Adapter_OnBoat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "OffBoat",
			Handler:       _Adapter_OffBoat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "BoatStatus",
			Handler:       _Adapter_BoatStatus_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Arrived",
			Handler:       _Adapter_Arrived_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/adapter.proto",
}
