// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/adapter.proto

package adapter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServiceState represents enum values for the following states of the
// boats
type ServiceState int32

const (
	ServiceState_UNKNOWN     ServiceState = 0
	ServiceState_ON_TIME     ServiceState = 1
	ServiceState_DELAYED     ServiceState = 2
	ServiceState_UNAVAILABLE ServiceState = 3
)

// Enum value maps for ServiceState.
var (
	ServiceState_name = map[int32]string{
		0: "UNKNOWN",
		1: "ON_TIME",
		2: "DELAYED",
		3: "UNAVAILABLE",
	}
	ServiceState_value = map[string]int32{
		"UNKNOWN":     0,
		"ON_TIME":     1,
		"DELAYED":     2,
		"UNAVAILABLE": 3,
	}
)

func (x ServiceState) Enum() *ServiceState {
	p := new(ServiceState)
	*p = x
	return p
}

func (x ServiceState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_adapter_proto_enumTypes[0].Descriptor()
}

func (ServiceState) Type() protoreflect.EnumType {
	return &file_proto_adapter_proto_enumTypes[0]
}

func (x ServiceState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceState.Descriptor instead.
func (ServiceState) EnumDescriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{0}
}

// Address represents the number and street name of an address where a dock is
// located
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Street        string                 `protobuf:"bytes,2,opt,name=street,proto3" json:"street,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_proto_adapter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

// Dock represents the address and gangway combination where the client will
// board the boat
type Dock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *Address               `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Gangway       string                 `protobuf:"bytes,2,opt,name=gangway,proto3" json:"gangway,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dock) Reset() {
	*x = Dock{}
	mi := &file_proto_adapter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dock) ProtoMessage() {}

func (x *Dock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dock.ProtoReflect.Descriptor instead.
func (*Dock) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{1}
}

func (x *Dock) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Dock) GetGangway() string {
	if x != nil {
		return x.Gangway
	}
	return ""
}

// Boat represents the data for individual boats
type Boat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoatId        int32                  `protobuf:"varint,1,opt,name=boat_id,json=boatId,proto3" json:"boat_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Boat) Reset() {
	*x = Boat{}
	mi := &file_proto_adapter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Boat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Boat) ProtoMessage() {}

func (x *Boat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Boat.ProtoReflect.Descriptor instead.
func (*Boat) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{2}
}

func (x *Boat) GetBoatId() int32 {
	if x != nil {
		return x.BoatId
	}
	return 0
}

func (x *Boat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ClientData holds the client connection data that the Adapter needs to
// send messages
type ClientData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnName      string                 `protobuf:"bytes,1,opt,name=conn_name,json=connName,proto3" json:"conn_name,omitempty"`
	ConnType      string                 `protobuf:"bytes,2,opt,name=conn_type,json=connType,proto3" json:"conn_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientData) Reset() {
	*x = ClientData{}
	mi := &file_proto_adapter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientData) ProtoMessage() {}

func (x *ClientData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientData.ProtoReflect.Descriptor instead.
func (*ClientData) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{3}
}

func (x *ClientData) GetConnName() string {
	if x != nil {
		return x.ConnName
	}
	return ""
}

func (x *ClientData) GetConnType() string {
	if x != nil {
		return x.ConnType
	}
	return ""
}

// ReserveTripAPIMessage represents the ReserveTrip API message that a client
// sends to the MockLogic
type ReserveTripAPIMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// message_type is a const = "reserveTrip"
	MessageType     string `protobuf:"bytes,1,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	AuthToken       string `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	ClientId        string `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	SourceDock      *Dock  `protobuf:"bytes,5,opt,name=source_dock,json=sourceDock,proto3" json:"source_dock,omitempty"`
	DestinationDock *Dock  `protobuf:"bytes,6,opt,name=destination_dock,json=destinationDock,proto3" json:"destination_dock,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReserveTripAPIMessage) Reset() {
	*x = ReserveTripAPIMessage{}
	mi := &file_proto_adapter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveTripAPIMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveTripAPIMessage) ProtoMessage() {}

func (x *ReserveTripAPIMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveTripAPIMessage.ProtoReflect.Descriptor instead.
func (*ReserveTripAPIMessage) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{4}
}

func (x *ReserveTripAPIMessage) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *ReserveTripAPIMessage) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *ReserveTripAPIMessage) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ReserveTripAPIMessage) GetSourceDock() *Dock {
	if x != nil {
		return x.SourceDock
	}
	return nil
}

func (x *ReserveTripAPIMessage) GetDestinationDock() *Dock {
	if x != nil {
		return x.DestinationDock
	}
	return nil
}

// AckAPIMessage represents the Ack API message that the MockLogic
// sends to a client indicating that a ReserveTrip message is being processed
type AckAPIMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// message_type is a const = "ack"
	MessageType   string `protobuf:"bytes,1,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	ClientId      string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	IsReserved    bool   `protobuf:"varint,3,opt,name=is_reserved,json=isReserved,proto3" json:"is_reserved,omitempty"`
	Boat          *Boat  `protobuf:"bytes,4,opt,name=boat,proto3" json:"boat,omitempty"`
	TransactionId string `protobuf:"bytes,5,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckAPIMessage) Reset() {
	*x = AckAPIMessage{}
	mi := &file_proto_adapter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckAPIMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckAPIMessage) ProtoMessage() {}

func (x *AckAPIMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckAPIMessage.ProtoReflect.Descriptor instead.
func (*AckAPIMessage) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{5}
}

func (x *AckAPIMessage) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *AckAPIMessage) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AckAPIMessage) GetIsReserved() bool {
	if x != nil {
		return x.IsReserved
	}
	return false
}

func (x *AckAPIMessage) GetBoat() *Boat {
	if x != nil {
		return x.Boat
	}
	return nil
}

func (x *AckAPIMessage) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

// AtDockAPIMessage reperesents the AtDock API message that the client
// sends to the MockLogic
type AtDockAPIMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// message_type is a const = "atDock"
	MessageType   string `protobuf:"bytes,1,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	ClientId      string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Boat          *Boat  `protobuf:"bytes,3,opt,name=boat,proto3" json:"boat,omitempty"`
	Dock          *Dock  `protobuf:"bytes,4,opt,name=dock,proto3" json:"dock,omitempty"`
	TransactionId string `protobuf:"bytes,5,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AtDockAPIMessage) Reset() {
	*x = AtDockAPIMessage{}
	mi := &file_proto_adapter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtDockAPIMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtDockAPIMessage) ProtoMessage() {}

func (x *AtDockAPIMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtDockAPIMessage.ProtoReflect.Descriptor instead.
func (*AtDockAPIMessage) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{6}
}

func (x *AtDockAPIMessage) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *AtDockAPIMessage) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AtDockAPIMessage) GetBoat() *Boat {
	if x != nil {
		return x.Boat
	}
	return nil
}

func (x *AtDockAPIMessage) GetDock() *Dock {
	if x != nil {
		return x.Dock
	}
	return nil
}

func (x *AtDockAPIMessage) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

// OnBoatAPIMessage reperesents the OnBoat API message that the client
// sends to the MockLogic
type OnBoatAPIMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// message_type is a const = "onBoat"
	MessageType   string `protobuf:"bytes,1,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	ClientId      string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Boat          *Boat  `protobuf:"bytes,3,opt,name=boat,proto3" json:"boat,omitempty"`
	TransactionId string `protobuf:"bytes,4,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnBoatAPIMessage) Reset() {
	*x = OnBoatAPIMessage{}
	mi := &file_proto_adapter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnBoatAPIMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnBoatAPIMessage) ProtoMessage() {}

func (x *OnBoatAPIMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnBoatAPIMessage.ProtoReflect.Descriptor instead.
func (*OnBoatAPIMessage) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{7}
}

func (x *OnBoatAPIMessage) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *OnBoatAPIMessage) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *OnBoatAPIMessage) GetBoat() *Boat {
	if x != nil {
		return x.Boat
	}
	return nil
}

func (x *OnBoatAPIMessage) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

// OffBoatAPIMessage reperesents the OffBoat API message that the client
// sends to the MockLogic
type OffBoatAPIMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// message_type is a const = "offBoat"
	MessageType   string `protobuf:"bytes,1,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	ClientId      string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Boat          *Boat  `protobuf:"bytes,3,opt,name=boat,proto3" json:"boat,omitempty"`
	TransactionId string `protobuf:"bytes,4,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OffBoatAPIMessage) Reset() {
	*x = OffBoatAPIMessage{}
	mi := &file_proto_adapter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OffBoatAPIMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OffBoatAPIMessage) ProtoMessage() {}

func (x *OffBoatAPIMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OffBoatAPIMessage.ProtoReflect.Descriptor instead.
func (*OffBoatAPIMessage) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{8}
}

func (x *OffBoatAPIMessage) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *OffBoatAPIMessage) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *OffBoatAPIMessage) GetBoat() *Boat {
	if x != nil {
		return x.Boat
	}
	return nil
}

func (x *OffBoatAPIMessage) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

// BoatStatusAPIMessage represents the BoatStatus API message that the MockLogic
// sends to all clients
type BoatStatusAPIMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// message_type is a const = "boatStatus"
	MessageType   string       `protobuf:"bytes,1,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	Boat          *Boat        `protobuf:"bytes,2,opt,name=boat,proto3" json:"boat,omitempty"`
	ServiceState  ServiceState `protobuf:"varint,3,opt,name=service_state,json=serviceState,proto3,enum=adapter.ServiceState" json:"service_state,omitempty"`
	PreviousDock  *Dock        `protobuf:"bytes,4,opt,name=previous_dock,json=previousDock,proto3" json:"previous_dock,omitempty"`
	CurrentDock   *Dock        `protobuf:"bytes,5,opt,name=current_dock,json=currentDock,proto3" json:"current_dock,omitempty"`
	NextDock      *Dock        `protobuf:"bytes,6,opt,name=next_dock,json=nextDock,proto3" json:"next_dock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoatStatusAPIMessage) Reset() {
	*x = BoatStatusAPIMessage{}
	mi := &file_proto_adapter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoatStatusAPIMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoatStatusAPIMessage) ProtoMessage() {}

func (x *BoatStatusAPIMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoatStatusAPIMessage.ProtoReflect.Descriptor instead.
func (*BoatStatusAPIMessage) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{9}
}

func (x *BoatStatusAPIMessage) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *BoatStatusAPIMessage) GetBoat() *Boat {
	if x != nil {
		return x.Boat
	}
	return nil
}

func (x *BoatStatusAPIMessage) GetServiceState() ServiceState {
	if x != nil {
		return x.ServiceState
	}
	return ServiceState_UNKNOWN
}

func (x *BoatStatusAPIMessage) GetPreviousDock() *Dock {
	if x != nil {
		return x.PreviousDock
	}
	return nil
}

func (x *BoatStatusAPIMessage) GetCurrentDock() *Dock {
	if x != nil {
		return x.CurrentDock
	}
	return nil
}

func (x *BoatStatusAPIMessage) GetNextDock() *Dock {
	if x != nil {
		return x.NextDock
	}
	return nil
}

// ArrivedAPIMessage reperesents the Arrived API message that the
// MockLogic sends to the client
type ArrivedAPIMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// message_type is a const = "arrived"
	MessageType   string `protobuf:"bytes,1,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	ClientId      string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Boat          *Boat  `protobuf:"bytes,3,opt,name=boat,proto3" json:"boat,omitempty"`
	Dock          *Dock  `protobuf:"bytes,4,opt,name=dock,proto3" json:"dock,omitempty"`
	TransactionId string `protobuf:"bytes,5,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrivedAPIMessage) Reset() {
	*x = ArrivedAPIMessage{}
	mi := &file_proto_adapter_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrivedAPIMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrivedAPIMessage) ProtoMessage() {}

func (x *ArrivedAPIMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrivedAPIMessage.ProtoReflect.Descriptor instead.
func (*ArrivedAPIMessage) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{10}
}

func (x *ArrivedAPIMessage) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *ArrivedAPIMessage) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ArrivedAPIMessage) GetBoat() *Boat {
	if x != nil {
		return x.Boat
	}
	return nil
}

func (x *ArrivedAPIMessage) GetDock() *Dock {
	if x != nil {
		return x.Dock
	}
	return nil
}

func (x *ArrivedAPIMessage) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

// ReserveTripMessage represents the Reserve API message and the client
// connection data that the Adapter uses
type ReserveTripMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiMessage    *ReserveTripAPIMessage `protobuf:"bytes,1,opt,name=api_message,json=apiMessage,proto3" json:"api_message,omitempty"`
	ClientData    *ClientData            `protobuf:"bytes,2,opt,name=client_data,json=clientData,proto3" json:"client_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveTripMessage) Reset() {
	*x = ReserveTripMessage{}
	mi := &file_proto_adapter_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveTripMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveTripMessage) ProtoMessage() {}

func (x *ReserveTripMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveTripMessage.ProtoReflect.Descriptor instead.
func (*ReserveTripMessage) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{11}
}

func (x *ReserveTripMessage) GetApiMessage() *ReserveTripAPIMessage {
	if x != nil {
		return x.ApiMessage
	}
	return nil
}

func (x *ReserveTripMessage) GetClientData() *ClientData {
	if x != nil {
		return x.ClientData
	}
	return nil
}

// AckMessage represents the Ack API message and the client
// connection data that the Adapter uses
type AckMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiMessage    *AckAPIMessage         `protobuf:"bytes,1,opt,name=api_message,json=apiMessage,proto3" json:"api_message,omitempty"`
	ClientData    *ClientData            `protobuf:"bytes,2,opt,name=client_data,json=clientData,proto3" json:"client_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckMessage) Reset() {
	*x = AckMessage{}
	mi := &file_proto_adapter_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMessage) ProtoMessage() {}

func (x *AckMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMessage.ProtoReflect.Descriptor instead.
func (*AckMessage) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{12}
}

func (x *AckMessage) GetApiMessage() *AckAPIMessage {
	if x != nil {
		return x.ApiMessage
	}
	return nil
}

func (x *AckMessage) GetClientData() *ClientData {
	if x != nil {
		return x.ClientData
	}
	return nil
}

// AtDockMessage represents the AtDock API message and the client
// connection data that the Adapter uses
type AtDockMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiMessage    *AtDockAPIMessage      `protobuf:"bytes,1,opt,name=api_message,json=apiMessage,proto3" json:"api_message,omitempty"`
	ClientData    *ClientData            `protobuf:"bytes,2,opt,name=client_data,json=clientData,proto3" json:"client_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AtDockMessage) Reset() {
	*x = AtDockMessage{}
	mi := &file_proto_adapter_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtDockMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtDockMessage) ProtoMessage() {}

func (x *AtDockMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtDockMessage.ProtoReflect.Descriptor instead.
func (*AtDockMessage) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{13}
}

func (x *AtDockMessage) GetApiMessage() *AtDockAPIMessage {
	if x != nil {
		return x.ApiMessage
	}
	return nil
}

func (x *AtDockMessage) GetClientData() *ClientData {
	if x != nil {
		return x.ClientData
	}
	return nil
}

// OnBoatMessage represents the OnBoat API message and the client
// connection data that the Adapter uses
type OnBoatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiMessage    *OnBoatAPIMessage      `protobuf:"bytes,1,opt,name=api_message,json=apiMessage,proto3" json:"api_message,omitempty"`
	ClientData    *ClientData            `protobuf:"bytes,2,opt,name=client_data,json=clientData,proto3" json:"client_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnBoatMessage) Reset() {
	*x = OnBoatMessage{}
	mi := &file_proto_adapter_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnBoatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnBoatMessage) ProtoMessage() {}

func (x *OnBoatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnBoatMessage.ProtoReflect.Descriptor instead.
func (*OnBoatMessage) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{14}
}

func (x *OnBoatMessage) GetApiMessage() *OnBoatAPIMessage {
	if x != nil {
		return x.ApiMessage
	}
	return nil
}

func (x *OnBoatMessage) GetClientData() *ClientData {
	if x != nil {
		return x.ClientData
	}
	return nil
}

// OffBoatMessage represents the OffBoat API message and the client
// connection data that the Adapter uses
type OffBoatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiMessage    *OffBoatAPIMessage     `protobuf:"bytes,1,opt,name=api_message,json=apiMessage,proto3" json:"api_message,omitempty"`
	ClientData    *ClientData            `protobuf:"bytes,2,opt,name=client_data,json=clientData,proto3" json:"client_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OffBoatMessage) Reset() {
	*x = OffBoatMessage{}
	mi := &file_proto_adapter_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OffBoatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OffBoatMessage) ProtoMessage() {}

func (x *OffBoatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OffBoatMessage.ProtoReflect.Descriptor instead.
func (*OffBoatMessage) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{15}
}

func (x *OffBoatMessage) GetApiMessage() *OffBoatAPIMessage {
	if x != nil {
		return x.ApiMessage
	}
	return nil
}

func (x *OffBoatMessage) GetClientData() *ClientData {
	if x != nil {
		return x.ClientData
	}
	return nil
}

// BoatStatusMessage represents the BoatStatus API message and the client
// connection data that the Adapter uses
type BoatStatusMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiMessage    *BoatStatusAPIMessage  `protobuf:"bytes,1,opt,name=api_message,json=apiMessage,proto3" json:"api_message,omitempty"`
	ClientData    *ClientData            `protobuf:"bytes,2,opt,name=client_data,json=clientData,proto3" json:"client_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoatStatusMessage) Reset() {
	*x = BoatStatusMessage{}
	mi := &file_proto_adapter_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoatStatusMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoatStatusMessage) ProtoMessage() {}

func (x *BoatStatusMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoatStatusMessage.ProtoReflect.Descriptor instead.
func (*BoatStatusMessage) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{16}
}

func (x *BoatStatusMessage) GetApiMessage() *BoatStatusAPIMessage {
	if x != nil {
		return x.ApiMessage
	}
	return nil
}

func (x *BoatStatusMessage) GetClientData() *ClientData {
	if x != nil {
		return x.ClientData
	}
	return nil
}

// ArrivedMessage represents the Arrived API message and the client
// connection data that the Adapter uses
type ArrivedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiMessage    *ArrivedAPIMessage     `protobuf:"bytes,1,opt,name=api_message,json=apiMessage,proto3" json:"api_message,omitempty"`
	ClientData    *ClientData            `protobuf:"bytes,2,opt,name=client_data,json=clientData,proto3" json:"client_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrivedMessage) Reset() {
	*x = ArrivedMessage{}
	mi := &file_proto_adapter_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrivedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrivedMessage) ProtoMessage() {}

func (x *ArrivedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrivedMessage.ProtoReflect.Descriptor instead.
func (*ArrivedMessage) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{17}
}

func (x *ArrivedMessage) GetApiMessage() *ArrivedAPIMessage {
	if x != nil {
		return x.ApiMessage
	}
	return nil
}

func (x *ArrivedMessage) GetClientData() *ClientData {
	if x != nil {
		return x.ClientData
	}
	return nil
}

// Empty represents an empty message that is not expected to
// ever be sent or received and is used for one half of a
// bi-directional streaming message service
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_adapter_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{18}
}

var File_proto_adapter_proto protoreflect.FileDescriptor

const file_proto_adapter_proto_rawDesc = "" +
	"\n" +
	"\x13proto/adapter.proto\x12\aadapter\"9\n" +
	"\aAddress\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\x12\x16\n" +
	"\x06street\x18\x02 \x01(\tR\x06street\"L\n" +
	"\x04Dock\x12*\n" +
	"\aaddress\x18\x01 \x01(\v2\x10.adapter.AddressR\aaddress\x12\x18\n" +
	"\agangway\x18\x02 \x01(\tR\agangway\"3\n" +
	"\x04Boat\x12\x17\n" +
	"\aboat_id\x18\x01 \x01(\x05R\x06boatId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"F\n" +
	"\n" +
	"ClientData\x12\x1b\n" +
	"\tconn_name\x18\x01 \x01(\tR\bconnName\x12\x1b\n" +
	"\tconn_type\x18\x02 \x01(\tR\bconnType\"\xe0\x01\n" +
	"\x15ReserveTripAPIMessage\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\tR\vmessageType\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\tR\tauthToken\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12.\n" +
	"\vsource_dock\x18\x05 \x01(\v2\r.adapter.DockR\n" +
	"sourceDock\x128\n" +
	"\x10destination_dock\x18\x06 \x01(\v2\r.adapter.DockR\x0fdestinationDock\"\xba\x01\n" +
	"\rAckAPIMessage\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\tR\vmessageType\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x1f\n" +
	"\vis_reserved\x18\x03 \x01(\bR\n" +
	"isReserved\x12!\n" +
	"\x04boat\x18\x04 \x01(\v2\r.adapter.BoatR\x04boat\x12%\n" +
	"\x0etransaction_id\x18\x05 \x01(\tR\rtransactionId\"\xbf\x01\n" +
	"\x10AtDockAPIMessage\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\tR\vmessageType\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12!\n" +
	"\x04boat\x18\x03 \x01(\v2\r.adapter.BoatR\x04boat\x12!\n" +
	"\x04dock\x18\x04 \x01(\v2\r.adapter.DockR\x04dock\x12%\n" +
	"\x0etransaction_id\x18\x05 \x01(\tR\rtransactionId\"\x9c\x01\n" +
	"\x10OnBoatAPIMessage\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\tR\vmessageType\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12!\n" +
	"\x04boat\x18\x03 \x01(\v2\r.adapter.BoatR\x04boat\x12%\n" +
	"\x0etransaction_id\x18\x04 \x01(\tR\rtransactionId\"\x9d\x01\n" +
	"\x11OffBoatAPIMessage\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\tR\vmessageType\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12!\n" +
	"\x04boat\x18\x03 \x01(\v2\r.adapter.BoatR\x04boat\x12%\n" +
	"\x0etransaction_id\x18\x04 \x01(\tR\rtransactionId\"\xaa\x02\n" +
	"\x14BoatStatusAPIMessage\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\tR\vmessageType\x12!\n" +
	"\x04boat\x18\x02 \x01(\v2\r.adapter.BoatR\x04boat\x12:\n" +
	"\rservice_state\x18\x03 \x01(\x0e2\x15.adapter.ServiceStateR\fserviceState\x122\n" +
	"\rprevious_dock\x18\x04 \x01(\v2\r.adapter.DockR\fpreviousDock\x120\n" +
	"\fcurrent_dock\x18\x05 \x01(\v2\r.adapter.DockR\vcurrentDock\x12*\n" +
	"\tnext_dock\x18\x06 \x01(\v2\r.adapter.DockR\bnextDock\"\xc0\x01\n" +
	"\x11ArrivedAPIMessage\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\tR\vmessageType\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12!\n" +
	"\x04boat\x18\x03 \x01(\v2\r.adapter.BoatR\x04boat\x12!\n" +
	"\x04dock\x18\x04 \x01(\v2\r.adapter.DockR\x04dock\x12%\n" +
	"\x0etransaction_id\x18\x05 \x01(\tR\rtransactionId\"\x8b\x01\n" +
	"\x12ReserveTripMessage\x12?\n" +
	"\vapi_message\x18\x01 \x01(\v2\x1e.adapter.ReserveTripAPIMessageR\n" +
	"apiMessage\x124\n" +
	"\vclient_data\x18\x02 \x01(\v2\x13.adapter.ClientDataR\n" +
	"clientData\"{\n" +
	"\n" +
	"AckMessage\x127\n" +
	"\vapi_message\x18\x01 \x01(\v2\x16.adapter.AckAPIMessageR\n" +
	"apiMessage\x124\n" +
	"\vclient_data\x18\x02 \x01(\v2\x13.adapter.ClientDataR\n" +
	"clientData\"\x81\x01\n" +
	"\rAtDockMessage\x12:\n" +
	"\vapi_message\x18\x01 \x01(\v2\x19.adapter.AtDockAPIMessageR\n" +
	"apiMessage\x124\n" +
	"\vclient_data\x18\x02 \x01(\v2\x13.adapter.ClientDataR\n" +
	"clientData\"\x81\x01\n" +
	"\rOnBoatMessage\x12:\n" +
	"\vapi_message\x18\x01 \x01(\v2\x19.adapter.OnBoatAPIMessageR\n" +
	"apiMessage\x124\n" +
	"\vclient_data\x18\x02 \x01(\v2\x13.adapter.ClientDataR\n" +
	"clientData\"\x83\x01\n" +
	"\x0eOffBoatMessage\x12;\n" +
	"\vapi_message\x18\x01 \x01(\v2\x1a.adapter.OffBoatAPIMessageR\n" +
	"apiMessage\x124\n" +
	"\vclient_data\x18\x02 \x01(\v2\x13.adapter.ClientDataR\n" +
	"clientData\"\x89\x01\n" +
	"\x11BoatStatusMessage\x12>\n" +
	"\vapi_message\x18\x01 \x01(\v2\x1d.adapter.BoatStatusAPIMessageR\n" +
	"apiMessage\x124\n" +
	"\vclient_data\x18\x02 \x01(\v2\x13.adapter.ClientDataR\n" +
	"clientData\"\x83\x01\n" +
	"\x0eArrivedMessage\x12;\n" +
	"\vapi_message\x18\x01 \x01(\v2\x1a.adapter.ArrivedAPIMessageR\n" +
	"apiMessage\x124\n" +
	"\vclient_data\x18\x02 \x01(\v2\x13.adapter.ClientDataR\n" +
	"clientData\"\a\n" +
	"\x05Empty*F\n" +
	"\fServiceState\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aON_TIME\x10\x01\x12\v\n" +
	"\aDELAYED\x10\x02\x12\x0f\n" +
	"\vUNAVAILABLE\x10\x032\xa1\x03\n" +
	"\aAdapter\x12@\n" +
	"\vReserveTrip\x12\x0e.adapter.Empty\x1a\x1b.adapter.ReserveTripMessage\"\x00(\x010\x01\x120\n" +
	"\x03Ack\x12\x13.adapter.AckMessage\x1a\x0e.adapter.Empty\"\x00(\x010\x01\x126\n" +
	"\x06AtDock\x12\x0e.adapter.Empty\x1a\x16.adapter.AtDockMessage\"\x00(\x010\x01\x126\n" +
	"\x06OnBoat\x12\x0e.adapter.Empty\x1a\x16.adapter.OnBoatMessage\"\x00(\x010\x01\x128\n" +
	"\aOffBoat\x12\x0e.adapter.Empty\x1a\x17.adapter.OffBoatMessage\"\x00(\x010\x01\x12>\n" +
	"\n" +
	"BoatStatus\x12\x1a.adapter.BoatStatusMessage\x1a\x0e.adapter.Empty\"\x00(\x010\x01\x128\n" +
	"\aArrived\x12\x17.adapter.ArrivedMessage\x1a\x0e.adapter.Empty\"\x00(\x010\x01B\x17Z\x15riden/adapter/adapterb\x06proto3"

var (
	file_proto_adapter_proto_rawDescOnce sync.Once
	file_proto_adapter_proto_rawDescData []byte
)

func file_proto_adapter_proto_rawDescGZIP() []byte {
	file_proto_adapter_proto_rawDescOnce.Do(func() {
		file_proto_adapter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_adapter_proto_rawDesc), len(file_proto_adapter_proto_rawDesc)))
	})
	return file_proto_adapter_proto_rawDescData
}

var file_proto_adapter_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_adapter_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_adapter_proto_goTypes = []any{
	(ServiceState)(0),             // 0: adapter.ServiceState
	(*Address)(nil),               // 1: adapter.Address
	(*Dock)(nil),                  // 2: adapter.Dock
	(*Boat)(nil),                  // 3: adapter.Boat
	(*ClientData)(nil),            // 4: adapter.ClientData
	(*ReserveTripAPIMessage)(nil), // 5: adapter.ReserveTripAPIMessage
	(*AckAPIMessage)(nil),         // 6: adapter.AckAPIMessage
	(*AtDockAPIMessage)(nil),      // 7: adapter.AtDockAPIMessage
	(*OnBoatAPIMessage)(nil),      // 8: adapter.OnBoatAPIMessage
	(*OffBoatAPIMessage)(nil),     // 9: adapter.OffBoatAPIMessage
	(*BoatStatusAPIMessage)(nil),  // 10: adapter.BoatStatusAPIMessage
	(*ArrivedAPIMessage)(nil),     // 11: adapter.ArrivedAPIMessage
	(*ReserveTripMessage)(nil),    // 12: adapter.ReserveTripMessage
	(*AckMessage)(nil),            // 13: adapter.AckMessage
	(*AtDockMessage)(nil),         // 14: adapter.AtDockMessage
	(*OnBoatMessage)(nil),         // 15: adapter.OnBoatMessage
	(*OffBoatMessage)(nil),        // 16: adapter.OffBoatMessage
	(*BoatStatusMessage)(nil),     // 17: adapter.BoatStatusMessage
	(*ArrivedMessage)(nil),        // 18: adapter.ArrivedMessage
	(*Empty)(nil),                 // 19: adapter.Empty
}
var file_proto_adapter_proto_depIdxs = []int32{
	1,  // 0: adapter.Dock.address:type_name -> adapter.Address
	2,  // 1: adapter.ReserveTripAPIMessage.source_dock:type_name -> adapter.Dock
	2,  // 2: adapter.ReserveTripAPIMessage.destination_dock:type_name -> adapter.Dock
	3,  // 3: adapter.AckAPIMessage.boat:type_name -> adapter.Boat
	3,  // 4: adapter.AtDockAPIMessage.boat:type_name -> adapter.Boat
	2,  // 5: adapter.AtDockAPIMessage.dock:type_name -> adapter.Dock
	3,  // 6: adapter.OnBoatAPIMessage.boat:type_name -> adapter.Boat
	3,  // 7: adapter.OffBoatAPIMessage.boat:type_name -> adapter.Boat
	3,  // 8: adapter.BoatStatusAPIMessage.boat:type_name -> adapter.Boat
	0,  // 9: adapter.BoatStatusAPIMessage.service_state:type_name -> adapter.ServiceState
	2,  // 10: adapter.BoatStatusAPIMessage.previous_dock:type_name -> adapter.Dock
	2,  // 11: adapter.BoatStatusAPIMessage.current_dock:type_name -> adapter.Dock
	2,  // 12: adapter.BoatStatusAPIMessage.next_dock:type_name -> adapter.Dock
	3,  // 13: adapter.ArrivedAPIMessage.boat:type_name -> adapter.Boat
	2,  // 14: adapter.ArrivedAPIMessage.dock:type_name -> adapter.Dock
	5,  // 15: adapter.ReserveTripMessage.api_message:type_name -> adapter.ReserveTripAPIMessage
	4,  // 16: adapter.ReserveTripMessage.client_data:type_name -> adapter.ClientData
	6,  // 17: adapter.AckMessage.api_message:type_name -> adapter.AckAPIMessage
	4,  // 18: adapter.AckMessage.client_data:type_name -> adapter.ClientData
	7,  // 19: adapter.AtDockMessage.api_message:type_name -> adapter.AtDockAPIMessage
	4,  // 20: adapter.AtDockMessage.client_data:type_name -> adapter.ClientData
	8,  // 21: adapter.OnBoatMessage.api_message:type_name -> adapter.OnBoatAPIMessage
	4,  // 22: adapter.OnBoatMessage.client_data:type_name -> adapter.ClientData
	9,  // 23: adapter.OffBoatMessage.api_message:type_name -> adapter.OffBoatAPIMessage
	4,  // 24: adapter.OffBoatMessage.client_data:type_name -> adapter.ClientData
	10, // 25: adapter.BoatStatusMessage.api_message:type_name -> adapter.BoatStatusAPIMessage
	4,  // 26: adapter.BoatStatusMessage.client_data:type_name -> adapter.ClientData
	11, // 27: adapter.ArrivedMessage.api_message:type_name -> adapter.ArrivedAPIMessage
	4,  // 28: adapter.ArrivedMessage.client_data:type_name -> adapter.ClientData
	19, // 29: adapter.Adapter.ReserveTrip:input_type -> adapter.Empty
	13, // 30: adapter.Adapter.Ack:input_type -> adapter.AckMessage
	19, // 31: adapter.Adapter.AtDock:input_type -> adapter.Empty
	19, // 32: adapter.Adapter.OnBoat:input_type -> adapter.Empty
	19, // 33: adapter.Adapter.OffBoat:input_type -> adapter.Empty
	17, // 34: adapter.Adapter.BoatStatus:input_type -> adapter.BoatStatusMessage
	18, // 35: adapter.Adapter.Arrived:input_type -> adapter.ArrivedMessage
	12, // 36: adapter.Adapter.ReserveTrip:output_type -> adapter.ReserveTripMessage
	19, // 37: adapter.Adapter.Ack:output_type -> adapter.Empty
	14, // 38: adapter.Adapter.AtDock:output_type -> adapter.AtDockMessage
	15, // 39: adapter.Adapter.OnBoat:output_type -> adapter.OnBoatMessage
	16, // 40: adapter.Adapter.OffBoat:output_type -> adapter.OffBoatMessage
	19, // 41: adapter.Adapter.BoatStatus:output_type -> adapter.Empty
	19, // 42: adapter.Adapter.Arrived:output_type -> adapter.Empty
	36, // [36:43] is the sub-list for method output_type
	29, // [29:36] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_proto_adapter_proto_init() }
func file_proto_adapter_proto_init() {
	if File_proto_adapter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_adapter_proto_rawDesc), len(file_proto_adapter_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_adapter_proto_goTypes,
		DependencyIndexes: file_proto_adapter_proto_depIdxs,
		EnumInfos:         file_proto_adapter_proto_enumTypes,
		MessageInfos:      file_proto_adapter_proto_msgTypes,
	}.Build()
	File_proto_adapter_proto = out.File
	file_proto_adapter_proto_goTypes = nil
	file_proto_adapter_proto_depIdxs = nil
}
