// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/adapter.proto

package adapter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServiceState represents enum values for the following states of the
// boats
type ServiceState int32

const (
	ServiceState_Unknown     ServiceState = 0
	ServiceState_OnTime      ServiceState = 1
	ServiceState_Delayed     ServiceState = 2
	ServiceState_Unavailable ServiceState = 3
)

// Enum value maps for ServiceState.
var (
	ServiceState_name = map[int32]string{
		0: "Unknown",
		1: "OnTime",
		2: "Delayed",
		3: "Unavailable",
	}
	ServiceState_value = map[string]int32{
		"Unknown":     0,
		"OnTime":      1,
		"Delayed":     2,
		"Unavailable": 3,
	}
)

func (x ServiceState) Enum() *ServiceState {
	p := new(ServiceState)
	*p = x
	return p
}

func (x ServiceState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_adapter_proto_enumTypes[0].Descriptor()
}

func (ServiceState) Type() protoreflect.EnumType {
	return &file_proto_adapter_proto_enumTypes[0]
}

func (x ServiceState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceState.Descriptor instead.
func (ServiceState) EnumDescriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{0}
}

// Address represents the number and street name of an address where a dock is
// located
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int32                  `protobuf:"varint,1,opt,name=Number,proto3" json:"Number,omitempty"`
	Street        string                 `protobuf:"bytes,2,opt,name=Street,proto3" json:"Street,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_proto_adapter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

// Dock represents the address and gangway combination where the client will
// board the boat
type Dock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *Address               `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Gangway       string                 `protobuf:"bytes,2,opt,name=Gangway,proto3" json:"Gangway,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dock) Reset() {
	*x = Dock{}
	mi := &file_proto_adapter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dock) ProtoMessage() {}

func (x *Dock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dock.ProtoReflect.Descriptor instead.
func (*Dock) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{1}
}

func (x *Dock) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Dock) GetGangway() string {
	if x != nil {
		return x.Gangway
	}
	return ""
}

// Boat represents the data for individual boats
type Boat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoatID        int32                  `protobuf:"varint,1,opt,name=BoatID,proto3" json:"BoatID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Boat) Reset() {
	*x = Boat{}
	mi := &file_proto_adapter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Boat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Boat) ProtoMessage() {}

func (x *Boat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Boat.ProtoReflect.Descriptor instead.
func (*Boat) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{2}
}

func (x *Boat) GetBoatID() int32 {
	if x != nil {
		return x.BoatID
	}
	return 0
}

func (x *Boat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ClientData holds the client connection data that the Adapter needs to
// send messages
type ClientData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnName      string                 `protobuf:"bytes,1,opt,name=ConnName,proto3" json:"ConnName,omitempty"`
	ConnType      string                 `protobuf:"bytes,2,opt,name=ConnType,proto3" json:"ConnType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientData) Reset() {
	*x = ClientData{}
	mi := &file_proto_adapter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientData) ProtoMessage() {}

func (x *ClientData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientData.ProtoReflect.Descriptor instead.
func (*ClientData) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{3}
}

func (x *ClientData) GetConnName() string {
	if x != nil {
		return x.ConnName
	}
	return ""
}

func (x *ClientData) GetConnType() string {
	if x != nil {
		return x.ConnType
	}
	return ""
}

// ReserveTripAPIMessage represents the ReserveTrip API message that a client
// sends to the MockLogic
type ReserveTripAPIMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MessageType is a const = "reserveTrip"
	MessageType     string `protobuf:"bytes,1,opt,name=MessageType,proto3" json:"MessageType,omitempty"`
	AuthToken       string `protobuf:"bytes,2,opt,name=AuthToken,proto3" json:"AuthToken,omitempty"`
	ClientID        string `protobuf:"bytes,3,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	SourceDock      *Dock  `protobuf:"bytes,5,opt,name=SourceDock,proto3" json:"SourceDock,omitempty"`
	DestinationDock *Dock  `protobuf:"bytes,6,opt,name=DestinationDock,proto3" json:"DestinationDock,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReserveTripAPIMessage) Reset() {
	*x = ReserveTripAPIMessage{}
	mi := &file_proto_adapter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveTripAPIMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveTripAPIMessage) ProtoMessage() {}

func (x *ReserveTripAPIMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveTripAPIMessage.ProtoReflect.Descriptor instead.
func (*ReserveTripAPIMessage) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{4}
}

func (x *ReserveTripAPIMessage) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *ReserveTripAPIMessage) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *ReserveTripAPIMessage) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *ReserveTripAPIMessage) GetSourceDock() *Dock {
	if x != nil {
		return x.SourceDock
	}
	return nil
}

func (x *ReserveTripAPIMessage) GetDestinationDock() *Dock {
	if x != nil {
		return x.DestinationDock
	}
	return nil
}

// AckAPIMessage represents the Ack API message that the MockLogic
// sends to a client indicating that a ReserveTrip message is being processed
type AckAPIMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MessageType is a const = "ack"
	MessageType   string `protobuf:"bytes,1,opt,name=MessageType,proto3" json:"MessageType,omitempty"`
	ClientID      string `protobuf:"bytes,2,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	IsReserved    bool   `protobuf:"varint,3,opt,name=IsReserved,proto3" json:"IsReserved,omitempty"`
	Boat          *Boat  `protobuf:"bytes,4,opt,name=Boat,proto3" json:"Boat,omitempty"`
	TransactionID string `protobuf:"bytes,5,opt,name=TransactionID,proto3" json:"TransactionID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckAPIMessage) Reset() {
	*x = AckAPIMessage{}
	mi := &file_proto_adapter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckAPIMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckAPIMessage) ProtoMessage() {}

func (x *AckAPIMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckAPIMessage.ProtoReflect.Descriptor instead.
func (*AckAPIMessage) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{5}
}

func (x *AckAPIMessage) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *AckAPIMessage) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *AckAPIMessage) GetIsReserved() bool {
	if x != nil {
		return x.IsReserved
	}
	return false
}

func (x *AckAPIMessage) GetBoat() *Boat {
	if x != nil {
		return x.Boat
	}
	return nil
}

func (x *AckAPIMessage) GetTransactionID() string {
	if x != nil {
		return x.TransactionID
	}
	return ""
}

// AtDockAPIMessage reperesents the AtDock API message that the client
// sends to the MockLogic
type AtDockAPIMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MessageType is a const = "atDock"
	MessageType   string `protobuf:"bytes,1,opt,name=MessageType,proto3" json:"MessageType,omitempty"`
	ClientID      string `protobuf:"bytes,2,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	Boat          *Boat  `protobuf:"bytes,3,opt,name=Boat,proto3" json:"Boat,omitempty"`
	Dock          *Dock  `protobuf:"bytes,4,opt,name=Dock,proto3" json:"Dock,omitempty"`
	TransactionID string `protobuf:"bytes,5,opt,name=TransactionID,proto3" json:"TransactionID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AtDockAPIMessage) Reset() {
	*x = AtDockAPIMessage{}
	mi := &file_proto_adapter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtDockAPIMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtDockAPIMessage) ProtoMessage() {}

func (x *AtDockAPIMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtDockAPIMessage.ProtoReflect.Descriptor instead.
func (*AtDockAPIMessage) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{6}
}

func (x *AtDockAPIMessage) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *AtDockAPIMessage) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *AtDockAPIMessage) GetBoat() *Boat {
	if x != nil {
		return x.Boat
	}
	return nil
}

func (x *AtDockAPIMessage) GetDock() *Dock {
	if x != nil {
		return x.Dock
	}
	return nil
}

func (x *AtDockAPIMessage) GetTransactionID() string {
	if x != nil {
		return x.TransactionID
	}
	return ""
}

// OnBoatAPIMessage reperesents the OnBoat API message that the client
// sends to the MockLogic
type OnBoatAPIMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MessageType is a const = "onBoat"
	MessageType   string `protobuf:"bytes,1,opt,name=MessageType,proto3" json:"MessageType,omitempty"`
	ClientID      string `protobuf:"bytes,2,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	Boat          *Boat  `protobuf:"bytes,3,opt,name=Boat,proto3" json:"Boat,omitempty"`
	TransactionID string `protobuf:"bytes,4,opt,name=TransactionID,proto3" json:"TransactionID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnBoatAPIMessage) Reset() {
	*x = OnBoatAPIMessage{}
	mi := &file_proto_adapter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnBoatAPIMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnBoatAPIMessage) ProtoMessage() {}

func (x *OnBoatAPIMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnBoatAPIMessage.ProtoReflect.Descriptor instead.
func (*OnBoatAPIMessage) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{7}
}

func (x *OnBoatAPIMessage) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *OnBoatAPIMessage) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *OnBoatAPIMessage) GetBoat() *Boat {
	if x != nil {
		return x.Boat
	}
	return nil
}

func (x *OnBoatAPIMessage) GetTransactionID() string {
	if x != nil {
		return x.TransactionID
	}
	return ""
}

// OffBoatAPIMessage reperesents the OffBoat API message that the client
// sends to the MockLogic
type OffBoatAPIMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MessageType is a const = "offBoat"
	MessageType   string `protobuf:"bytes,1,opt,name=MessageType,proto3" json:"MessageType,omitempty"`
	ClientID      string `protobuf:"bytes,2,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	Boat          *Boat  `protobuf:"bytes,3,opt,name=Boat,proto3" json:"Boat,omitempty"`
	TransactionID string `protobuf:"bytes,4,opt,name=TransactionID,proto3" json:"TransactionID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OffBoatAPIMessage) Reset() {
	*x = OffBoatAPIMessage{}
	mi := &file_proto_adapter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OffBoatAPIMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OffBoatAPIMessage) ProtoMessage() {}

func (x *OffBoatAPIMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OffBoatAPIMessage.ProtoReflect.Descriptor instead.
func (*OffBoatAPIMessage) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{8}
}

func (x *OffBoatAPIMessage) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *OffBoatAPIMessage) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *OffBoatAPIMessage) GetBoat() *Boat {
	if x != nil {
		return x.Boat
	}
	return nil
}

func (x *OffBoatAPIMessage) GetTransactionID() string {
	if x != nil {
		return x.TransactionID
	}
	return ""
}

// BoatStatusAPIMessage represents the BoatStatus API message that the MockLogic
// sends to all clients
type BoatStatusAPIMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MessageType is a const = "boatStatus"
	MessageType   string       `protobuf:"bytes,1,opt,name=MessageType,proto3" json:"MessageType,omitempty"`
	Boat          *Boat        `protobuf:"bytes,2,opt,name=Boat,proto3" json:"Boat,omitempty"`
	ServiceState  ServiceState `protobuf:"varint,3,opt,name=ServiceState,proto3,enum=adapter.ServiceState" json:"ServiceState,omitempty"`
	PreviousDock  *Dock        `protobuf:"bytes,4,opt,name=PreviousDock,proto3" json:"PreviousDock,omitempty"`
	CurrentDock   *Dock        `protobuf:"bytes,5,opt,name=CurrentDock,proto3" json:"CurrentDock,omitempty"`
	NextDock      *Dock        `protobuf:"bytes,6,opt,name=NextDock,proto3" json:"NextDock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoatStatusAPIMessage) Reset() {
	*x = BoatStatusAPIMessage{}
	mi := &file_proto_adapter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoatStatusAPIMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoatStatusAPIMessage) ProtoMessage() {}

func (x *BoatStatusAPIMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoatStatusAPIMessage.ProtoReflect.Descriptor instead.
func (*BoatStatusAPIMessage) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{9}
}

func (x *BoatStatusAPIMessage) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *BoatStatusAPIMessage) GetBoat() *Boat {
	if x != nil {
		return x.Boat
	}
	return nil
}

func (x *BoatStatusAPIMessage) GetServiceState() ServiceState {
	if x != nil {
		return x.ServiceState
	}
	return ServiceState_Unknown
}

func (x *BoatStatusAPIMessage) GetPreviousDock() *Dock {
	if x != nil {
		return x.PreviousDock
	}
	return nil
}

func (x *BoatStatusAPIMessage) GetCurrentDock() *Dock {
	if x != nil {
		return x.CurrentDock
	}
	return nil
}

func (x *BoatStatusAPIMessage) GetNextDock() *Dock {
	if x != nil {
		return x.NextDock
	}
	return nil
}

// ArrivedAPIMessage reperesents the Arrived API message that the
// MockLogic sends to the client
type ArrivedAPIMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MessageType is a const = "arrived"
	MessageType   string `protobuf:"bytes,1,opt,name=MessageType,proto3" json:"MessageType,omitempty"`
	ClientID      string `protobuf:"bytes,2,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	Boat          *Boat  `protobuf:"bytes,3,opt,name=Boat,proto3" json:"Boat,omitempty"`
	Dock          *Dock  `protobuf:"bytes,4,opt,name=Dock,proto3" json:"Dock,omitempty"`
	TransactionID string `protobuf:"bytes,5,opt,name=TransactionID,proto3" json:"TransactionID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrivedAPIMessage) Reset() {
	*x = ArrivedAPIMessage{}
	mi := &file_proto_adapter_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrivedAPIMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrivedAPIMessage) ProtoMessage() {}

func (x *ArrivedAPIMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrivedAPIMessage.ProtoReflect.Descriptor instead.
func (*ArrivedAPIMessage) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{10}
}

func (x *ArrivedAPIMessage) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *ArrivedAPIMessage) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *ArrivedAPIMessage) GetBoat() *Boat {
	if x != nil {
		return x.Boat
	}
	return nil
}

func (x *ArrivedAPIMessage) GetDock() *Dock {
	if x != nil {
		return x.Dock
	}
	return nil
}

func (x *ArrivedAPIMessage) GetTransactionID() string {
	if x != nil {
		return x.TransactionID
	}
	return ""
}

// ReserveTripMessage represents the Reserve API message and the client
// connection data that the Adapter uses
type ReserveTripMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	APIMessage    *ReserveTripAPIMessage `protobuf:"bytes,1,opt,name=APIMessage,proto3" json:"APIMessage,omitempty"`
	ClientData    *ClientData            `protobuf:"bytes,2,opt,name=ClientData,proto3" json:"ClientData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveTripMessage) Reset() {
	*x = ReserveTripMessage{}
	mi := &file_proto_adapter_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveTripMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveTripMessage) ProtoMessage() {}

func (x *ReserveTripMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveTripMessage.ProtoReflect.Descriptor instead.
func (*ReserveTripMessage) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{11}
}

func (x *ReserveTripMessage) GetAPIMessage() *ReserveTripAPIMessage {
	if x != nil {
		return x.APIMessage
	}
	return nil
}

func (x *ReserveTripMessage) GetClientData() *ClientData {
	if x != nil {
		return x.ClientData
	}
	return nil
}

// AckMessage represents the Ack API message and the client
// connection data that the Adapter uses
type AckMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	APIMessage    *AckAPIMessage         `protobuf:"bytes,1,opt,name=APIMessage,proto3" json:"APIMessage,omitempty"`
	ClientData    *ClientData            `protobuf:"bytes,2,opt,name=ClientData,proto3" json:"ClientData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckMessage) Reset() {
	*x = AckMessage{}
	mi := &file_proto_adapter_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMessage) ProtoMessage() {}

func (x *AckMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMessage.ProtoReflect.Descriptor instead.
func (*AckMessage) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{12}
}

func (x *AckMessage) GetAPIMessage() *AckAPIMessage {
	if x != nil {
		return x.APIMessage
	}
	return nil
}

func (x *AckMessage) GetClientData() *ClientData {
	if x != nil {
		return x.ClientData
	}
	return nil
}

// AtDockMessage represents the AtDock API message and the client
// connection data that the Adapter uses
type AtDockMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	APIMessage    *AtDockAPIMessage      `protobuf:"bytes,1,opt,name=APIMessage,proto3" json:"APIMessage,omitempty"`
	ClientData    *ClientData            `protobuf:"bytes,2,opt,name=ClientData,proto3" json:"ClientData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AtDockMessage) Reset() {
	*x = AtDockMessage{}
	mi := &file_proto_adapter_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtDockMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtDockMessage) ProtoMessage() {}

func (x *AtDockMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtDockMessage.ProtoReflect.Descriptor instead.
func (*AtDockMessage) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{13}
}

func (x *AtDockMessage) GetAPIMessage() *AtDockAPIMessage {
	if x != nil {
		return x.APIMessage
	}
	return nil
}

func (x *AtDockMessage) GetClientData() *ClientData {
	if x != nil {
		return x.ClientData
	}
	return nil
}

// OnBoatMessage represents the OnBoat API message and the client
// connection data that the Adapter uses
type OnBoatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	APIMessage    *OnBoatAPIMessage      `protobuf:"bytes,1,opt,name=APIMessage,proto3" json:"APIMessage,omitempty"`
	ClientData    *ClientData            `protobuf:"bytes,2,opt,name=ClientData,proto3" json:"ClientData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnBoatMessage) Reset() {
	*x = OnBoatMessage{}
	mi := &file_proto_adapter_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnBoatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnBoatMessage) ProtoMessage() {}

func (x *OnBoatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnBoatMessage.ProtoReflect.Descriptor instead.
func (*OnBoatMessage) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{14}
}

func (x *OnBoatMessage) GetAPIMessage() *OnBoatAPIMessage {
	if x != nil {
		return x.APIMessage
	}
	return nil
}

func (x *OnBoatMessage) GetClientData() *ClientData {
	if x != nil {
		return x.ClientData
	}
	return nil
}

// OffBoatMessage represents the OffBoat API message and the client
// connection data that the Adapter uses
type OffBoatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	APIMessage    *OffBoatAPIMessage     `protobuf:"bytes,1,opt,name=APIMessage,proto3" json:"APIMessage,omitempty"`
	ClientData    *ClientData            `protobuf:"bytes,2,opt,name=ClientData,proto3" json:"ClientData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OffBoatMessage) Reset() {
	*x = OffBoatMessage{}
	mi := &file_proto_adapter_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OffBoatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OffBoatMessage) ProtoMessage() {}

func (x *OffBoatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OffBoatMessage.ProtoReflect.Descriptor instead.
func (*OffBoatMessage) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{15}
}

func (x *OffBoatMessage) GetAPIMessage() *OffBoatAPIMessage {
	if x != nil {
		return x.APIMessage
	}
	return nil
}

func (x *OffBoatMessage) GetClientData() *ClientData {
	if x != nil {
		return x.ClientData
	}
	return nil
}

// BoatStatusMessage represents the BoatStatus API message and the client
// connection data that the Adapter uses
type BoatStatusMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	APIMessage    *BoatStatusAPIMessage  `protobuf:"bytes,1,opt,name=APIMessage,proto3" json:"APIMessage,omitempty"`
	ClientData    *ClientData            `protobuf:"bytes,2,opt,name=ClientData,proto3" json:"ClientData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoatStatusMessage) Reset() {
	*x = BoatStatusMessage{}
	mi := &file_proto_adapter_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoatStatusMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoatStatusMessage) ProtoMessage() {}

func (x *BoatStatusMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoatStatusMessage.ProtoReflect.Descriptor instead.
func (*BoatStatusMessage) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{16}
}

func (x *BoatStatusMessage) GetAPIMessage() *BoatStatusAPIMessage {
	if x != nil {
		return x.APIMessage
	}
	return nil
}

func (x *BoatStatusMessage) GetClientData() *ClientData {
	if x != nil {
		return x.ClientData
	}
	return nil
}

// ArrivedMessage represents the Arrived API message and the client
// connection data that the Adapter uses
type ArrivedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	APIMessage    *ArrivedAPIMessage     `protobuf:"bytes,1,opt,name=APIMessage,proto3" json:"APIMessage,omitempty"`
	ClientData    *ClientData            `protobuf:"bytes,2,opt,name=ClientData,proto3" json:"ClientData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrivedMessage) Reset() {
	*x = ArrivedMessage{}
	mi := &file_proto_adapter_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrivedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrivedMessage) ProtoMessage() {}

func (x *ArrivedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrivedMessage.ProtoReflect.Descriptor instead.
func (*ArrivedMessage) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{17}
}

func (x *ArrivedMessage) GetAPIMessage() *ArrivedAPIMessage {
	if x != nil {
		return x.APIMessage
	}
	return nil
}

func (x *ArrivedMessage) GetClientData() *ClientData {
	if x != nil {
		return x.ClientData
	}
	return nil
}

// Empty represents an empty message that is not expected to
// ever be sent or received and is used for one half of a
// bi-directional streaming message service
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_adapter_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adapter_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_adapter_proto_rawDescGZIP(), []int{18}
}

var File_proto_adapter_proto protoreflect.FileDescriptor

const file_proto_adapter_proto_rawDesc = "" +
	"\n" +
	"\x13proto/adapter.proto\x12\aadapter\"9\n" +
	"\aAddress\x12\x16\n" +
	"\x06Number\x18\x01 \x01(\x05R\x06Number\x12\x16\n" +
	"\x06Street\x18\x02 \x01(\tR\x06Street\"L\n" +
	"\x04Dock\x12*\n" +
	"\aAddress\x18\x01 \x01(\v2\x10.adapter.AddressR\aAddress\x12\x18\n" +
	"\aGangway\x18\x02 \x01(\tR\aGangway\"2\n" +
	"\x04Boat\x12\x16\n" +
	"\x06BoatID\x18\x01 \x01(\x05R\x06BoatID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\"D\n" +
	"\n" +
	"ClientData\x12\x1a\n" +
	"\bConnName\x18\x01 \x01(\tR\bConnName\x12\x1a\n" +
	"\bConnType\x18\x02 \x01(\tR\bConnType\"\xdb\x01\n" +
	"\x15ReserveTripAPIMessage\x12 \n" +
	"\vMessageType\x18\x01 \x01(\tR\vMessageType\x12\x1c\n" +
	"\tAuthToken\x18\x02 \x01(\tR\tAuthToken\x12\x1a\n" +
	"\bClientID\x18\x03 \x01(\tR\bClientID\x12-\n" +
	"\n" +
	"SourceDock\x18\x05 \x01(\v2\r.adapter.DockR\n" +
	"SourceDock\x127\n" +
	"\x0fDestinationDock\x18\x06 \x01(\v2\r.adapter.DockR\x0fDestinationDock\"\xb6\x01\n" +
	"\rAckAPIMessage\x12 \n" +
	"\vMessageType\x18\x01 \x01(\tR\vMessageType\x12\x1a\n" +
	"\bClientID\x18\x02 \x01(\tR\bClientID\x12\x1e\n" +
	"\n" +
	"IsReserved\x18\x03 \x01(\bR\n" +
	"IsReserved\x12!\n" +
	"\x04Boat\x18\x04 \x01(\v2\r.adapter.BoatR\x04Boat\x12$\n" +
	"\rTransactionID\x18\x05 \x01(\tR\rTransactionID\"\xbc\x01\n" +
	"\x10AtDockAPIMessage\x12 \n" +
	"\vMessageType\x18\x01 \x01(\tR\vMessageType\x12\x1a\n" +
	"\bClientID\x18\x02 \x01(\tR\bClientID\x12!\n" +
	"\x04Boat\x18\x03 \x01(\v2\r.adapter.BoatR\x04Boat\x12!\n" +
	"\x04Dock\x18\x04 \x01(\v2\r.adapter.DockR\x04Dock\x12$\n" +
	"\rTransactionID\x18\x05 \x01(\tR\rTransactionID\"\x99\x01\n" +
	"\x10OnBoatAPIMessage\x12 \n" +
	"\vMessageType\x18\x01 \x01(\tR\vMessageType\x12\x1a\n" +
	"\bClientID\x18\x02 \x01(\tR\bClientID\x12!\n" +
	"\x04Boat\x18\x03 \x01(\v2\r.adapter.BoatR\x04Boat\x12$\n" +
	"\rTransactionID\x18\x04 \x01(\tR\rTransactionID\"\x9a\x01\n" +
	"\x11OffBoatAPIMessage\x12 \n" +
	"\vMessageType\x18\x01 \x01(\tR\vMessageType\x12\x1a\n" +
	"\bClientID\x18\x02 \x01(\tR\bClientID\x12!\n" +
	"\x04Boat\x18\x03 \x01(\v2\r.adapter.BoatR\x04Boat\x12$\n" +
	"\rTransactionID\x18\x04 \x01(\tR\rTransactionID\"\xa5\x02\n" +
	"\x14BoatStatusAPIMessage\x12 \n" +
	"\vMessageType\x18\x01 \x01(\tR\vMessageType\x12!\n" +
	"\x04Boat\x18\x02 \x01(\v2\r.adapter.BoatR\x04Boat\x129\n" +
	"\fServiceState\x18\x03 \x01(\x0e2\x15.adapter.ServiceStateR\fServiceState\x121\n" +
	"\fPreviousDock\x18\x04 \x01(\v2\r.adapter.DockR\fPreviousDock\x12/\n" +
	"\vCurrentDock\x18\x05 \x01(\v2\r.adapter.DockR\vCurrentDock\x12)\n" +
	"\bNextDock\x18\x06 \x01(\v2\r.adapter.DockR\bNextDock\"\xbd\x01\n" +
	"\x11ArrivedAPIMessage\x12 \n" +
	"\vMessageType\x18\x01 \x01(\tR\vMessageType\x12\x1a\n" +
	"\bClientID\x18\x02 \x01(\tR\bClientID\x12!\n" +
	"\x04Boat\x18\x03 \x01(\v2\r.adapter.BoatR\x04Boat\x12!\n" +
	"\x04Dock\x18\x04 \x01(\v2\r.adapter.DockR\x04Dock\x12$\n" +
	"\rTransactionID\x18\x05 \x01(\tR\rTransactionID\"\x89\x01\n" +
	"\x12ReserveTripMessage\x12>\n" +
	"\n" +
	"APIMessage\x18\x01 \x01(\v2\x1e.adapter.ReserveTripAPIMessageR\n" +
	"APIMessage\x123\n" +
	"\n" +
	"ClientData\x18\x02 \x01(\v2\x13.adapter.ClientDataR\n" +
	"ClientData\"y\n" +
	"\n" +
	"AckMessage\x126\n" +
	"\n" +
	"APIMessage\x18\x01 \x01(\v2\x16.adapter.AckAPIMessageR\n" +
	"APIMessage\x123\n" +
	"\n" +
	"ClientData\x18\x02 \x01(\v2\x13.adapter.ClientDataR\n" +
	"ClientData\"\x7f\n" +
	"\rAtDockMessage\x129\n" +
	"\n" +
	"APIMessage\x18\x01 \x01(\v2\x19.adapter.AtDockAPIMessageR\n" +
	"APIMessage\x123\n" +
	"\n" +
	"ClientData\x18\x02 \x01(\v2\x13.adapter.ClientDataR\n" +
	"ClientData\"\x7f\n" +
	"\rOnBoatMessage\x129\n" +
	"\n" +
	"APIMessage\x18\x01 \x01(\v2\x19.adapter.OnBoatAPIMessageR\n" +
	"APIMessage\x123\n" +
	"\n" +
	"ClientData\x18\x02 \x01(\v2\x13.adapter.ClientDataR\n" +
	"ClientData\"\x81\x01\n" +
	"\x0eOffBoatMessage\x12:\n" +
	"\n" +
	"APIMessage\x18\x01 \x01(\v2\x1a.adapter.OffBoatAPIMessageR\n" +
	"APIMessage\x123\n" +
	"\n" +
	"ClientData\x18\x02 \x01(\v2\x13.adapter.ClientDataR\n" +
	"ClientData\"\x87\x01\n" +
	"\x11BoatStatusMessage\x12=\n" +
	"\n" +
	"APIMessage\x18\x01 \x01(\v2\x1d.adapter.BoatStatusAPIMessageR\n" +
	"APIMessage\x123\n" +
	"\n" +
	"ClientData\x18\x02 \x01(\v2\x13.adapter.ClientDataR\n" +
	"ClientData\"\x81\x01\n" +
	"\x0eArrivedMessage\x12:\n" +
	"\n" +
	"APIMessage\x18\x01 \x01(\v2\x1a.adapter.ArrivedAPIMessageR\n" +
	"APIMessage\x123\n" +
	"\n" +
	"ClientData\x18\x02 \x01(\v2\x13.adapter.ClientDataR\n" +
	"ClientData\"\a\n" +
	"\x05Empty*E\n" +
	"\fServiceState\x12\v\n" +
	"\aUnknown\x10\x00\x12\n" +
	"\n" +
	"\x06OnTime\x10\x01\x12\v\n" +
	"\aDelayed\x10\x02\x12\x0f\n" +
	"\vUnavailable\x10\x032\xa1\x03\n" +
	"\aAdapter\x12@\n" +
	"\vReserveTrip\x12\x0e.adapter.Empty\x1a\x1b.adapter.ReserveTripMessage\"\x00(\x010\x01\x120\n" +
	"\x03Ack\x12\x13.adapter.AckMessage\x1a\x0e.adapter.Empty\"\x00(\x010\x01\x126\n" +
	"\x06AtDock\x12\x0e.adapter.Empty\x1a\x16.adapter.AtDockMessage\"\x00(\x010\x01\x126\n" +
	"\x06OnBoat\x12\x0e.adapter.Empty\x1a\x16.adapter.OnBoatMessage\"\x00(\x010\x01\x128\n" +
	"\aOffBoat\x12\x0e.adapter.Empty\x1a\x17.adapter.OffBoatMessage\"\x00(\x010\x01\x12>\n" +
	"\n" +
	"BoatStatus\x12\x1a.adapter.BoatStatusMessage\x1a\x0e.adapter.Empty\"\x00(\x010\x01\x128\n" +
	"\aArrived\x12\x17.adapter.ArrivedMessage\x1a\x0e.adapter.Empty\"\x00(\x010\x01B\x17Z\x15riden/adapter/adapterb\x06proto3"

var (
	file_proto_adapter_proto_rawDescOnce sync.Once
	file_proto_adapter_proto_rawDescData []byte
)

func file_proto_adapter_proto_rawDescGZIP() []byte {
	file_proto_adapter_proto_rawDescOnce.Do(func() {
		file_proto_adapter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_adapter_proto_rawDesc), len(file_proto_adapter_proto_rawDesc)))
	})
	return file_proto_adapter_proto_rawDescData
}

var file_proto_adapter_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_adapter_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_adapter_proto_goTypes = []any{
	(ServiceState)(0),             // 0: adapter.ServiceState
	(*Address)(nil),               // 1: adapter.Address
	(*Dock)(nil),                  // 2: adapter.Dock
	(*Boat)(nil),                  // 3: adapter.Boat
	(*ClientData)(nil),            // 4: adapter.ClientData
	(*ReserveTripAPIMessage)(nil), // 5: adapter.ReserveTripAPIMessage
	(*AckAPIMessage)(nil),         // 6: adapter.AckAPIMessage
	(*AtDockAPIMessage)(nil),      // 7: adapter.AtDockAPIMessage
	(*OnBoatAPIMessage)(nil),      // 8: adapter.OnBoatAPIMessage
	(*OffBoatAPIMessage)(nil),     // 9: adapter.OffBoatAPIMessage
	(*BoatStatusAPIMessage)(nil),  // 10: adapter.BoatStatusAPIMessage
	(*ArrivedAPIMessage)(nil),     // 11: adapter.ArrivedAPIMessage
	(*ReserveTripMessage)(nil),    // 12: adapter.ReserveTripMessage
	(*AckMessage)(nil),            // 13: adapter.AckMessage
	(*AtDockMessage)(nil),         // 14: adapter.AtDockMessage
	(*OnBoatMessage)(nil),         // 15: adapter.OnBoatMessage
	(*OffBoatMessage)(nil),        // 16: adapter.OffBoatMessage
	(*BoatStatusMessage)(nil),     // 17: adapter.BoatStatusMessage
	(*ArrivedMessage)(nil),        // 18: adapter.ArrivedMessage
	(*Empty)(nil),                 // 19: adapter.Empty
}
var file_proto_adapter_proto_depIdxs = []int32{
	1,  // 0: adapter.Dock.Address:type_name -> adapter.Address
	2,  // 1: adapter.ReserveTripAPIMessage.SourceDock:type_name -> adapter.Dock
	2,  // 2: adapter.ReserveTripAPIMessage.DestinationDock:type_name -> adapter.Dock
	3,  // 3: adapter.AckAPIMessage.Boat:type_name -> adapter.Boat
	3,  // 4: adapter.AtDockAPIMessage.Boat:type_name -> adapter.Boat
	2,  // 5: adapter.AtDockAPIMessage.Dock:type_name -> adapter.Dock
	3,  // 6: adapter.OnBoatAPIMessage.Boat:type_name -> adapter.Boat
	3,  // 7: adapter.OffBoatAPIMessage.Boat:type_name -> adapter.Boat
	3,  // 8: adapter.BoatStatusAPIMessage.Boat:type_name -> adapter.Boat
	0,  // 9: adapter.BoatStatusAPIMessage.ServiceState:type_name -> adapter.ServiceState
	2,  // 10: adapter.BoatStatusAPIMessage.PreviousDock:type_name -> adapter.Dock
	2,  // 11: adapter.BoatStatusAPIMessage.CurrentDock:type_name -> adapter.Dock
	2,  // 12: adapter.BoatStatusAPIMessage.NextDock:type_name -> adapter.Dock
	3,  // 13: adapter.ArrivedAPIMessage.Boat:type_name -> adapter.Boat
	2,  // 14: adapter.ArrivedAPIMessage.Dock:type_name -> adapter.Dock
	5,  // 15: adapter.ReserveTripMessage.APIMessage:type_name -> adapter.ReserveTripAPIMessage
	4,  // 16: adapter.ReserveTripMessage.ClientData:type_name -> adapter.ClientData
	6,  // 17: adapter.AckMessage.APIMessage:type_name -> adapter.AckAPIMessage
	4,  // 18: adapter.AckMessage.ClientData:type_name -> adapter.ClientData
	7,  // 19: adapter.AtDockMessage.APIMessage:type_name -> adapter.AtDockAPIMessage
	4,  // 20: adapter.AtDockMessage.ClientData:type_name -> adapter.ClientData
	8,  // 21: adapter.OnBoatMessage.APIMessage:type_name -> adapter.OnBoatAPIMessage
	4,  // 22: adapter.OnBoatMessage.ClientData:type_name -> adapter.ClientData
	9,  // 23: adapter.OffBoatMessage.APIMessage:type_name -> adapter.OffBoatAPIMessage
	4,  // 24: adapter.OffBoatMessage.ClientData:type_name -> adapter.ClientData
	10, // 25: adapter.BoatStatusMessage.APIMessage:type_name -> adapter.BoatStatusAPIMessage
	4,  // 26: adapter.BoatStatusMessage.ClientData:type_name -> adapter.ClientData
	11, // 27: adapter.ArrivedMessage.APIMessage:type_name -> adapter.ArrivedAPIMessage
	4,  // 28: adapter.ArrivedMessage.ClientData:type_name -> adapter.ClientData
	19, // 29: adapter.Adapter.ReserveTrip:input_type -> adapter.Empty
	13, // 30: adapter.Adapter.Ack:input_type -> adapter.AckMessage
	19, // 31: adapter.Adapter.AtDock:input_type -> adapter.Empty
	19, // 32: adapter.Adapter.OnBoat:input_type -> adapter.Empty
	19, // 33: adapter.Adapter.OffBoat:input_type -> adapter.Empty
	17, // 34: adapter.Adapter.BoatStatus:input_type -> adapter.BoatStatusMessage
	18, // 35: adapter.Adapter.Arrived:input_type -> adapter.ArrivedMessage
	12, // 36: adapter.Adapter.ReserveTrip:output_type -> adapter.ReserveTripMessage
	19, // 37: adapter.Adapter.Ack:output_type -> adapter.Empty
	14, // 38: adapter.Adapter.AtDock:output_type -> adapter.AtDockMessage
	15, // 39: adapter.Adapter.OnBoat:output_type -> adapter.OnBoatMessage
	16, // 40: adapter.Adapter.OffBoat:output_type -> adapter.OffBoatMessage
	19, // 41: adapter.Adapter.BoatStatus:output_type -> adapter.Empty
	19, // 42: adapter.Adapter.Arrived:output_type -> adapter.Empty
	36, // [36:43] is the sub-list for method output_type
	29, // [29:36] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_proto_adapter_proto_init() }
func file_proto_adapter_proto_init() {
	if File_proto_adapter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_adapter_proto_rawDesc), len(file_proto_adapter_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_adapter_proto_goTypes,
		DependencyIndexes: file_proto_adapter_proto_depIdxs,
		EnumInfos:         file_proto_adapter_proto_enumTypes,
		MessageInfos:      file_proto_adapter_proto_msgTypes,
	}.Build()
	File_proto_adapter_proto = out.File
	file_proto_adapter_proto_goTypes = nil
	file_proto_adapter_proto_depIdxs = nil
}
